2025-01-25 23:19:13,547 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 334
-------------------
2025-01-25 23:19:40,336 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 334
-------------------
2025-01-25 23:19:59,654 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 334
-------------------
2025-01-25 23:19:59,753 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 354
-------------------
2025-01-25 23:19:59,753 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 266
-------------------
2025-01-25 23:19:59,753 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 269
-------------------
2025-01-25 23:19:59,753 [DEBUG] visa_bot - VFS Global sitesine giriş yapılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 209
-------------------
2025-01-25 23:19:59,819 [ERROR] visa_bot - Randevu kontrolü sırasında hata
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 262
-------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 1182, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        ssl_shutdown_timeout=ssl_shutdown_timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 1215, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/sslproto.py", line 560, in _do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 951, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 211, in check_appointments
    async with session.post(CONSULATE_URL, data=login_data) as response:
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        req, traces=traces, timeout=real_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<12 lines>...
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/aiohttp/connector.py", line 994, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host visa.vfsglobal.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)')]
2025-01-25 23:19:59,825 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 271
-------------------
2025-01-25 23:21:13,828 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 340
-------------------
2025-01-25 23:21:13,926 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 360
-------------------
2025-01-25 23:21:13,926 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 272
-------------------
2025-01-25 23:21:13,926 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 275
-------------------
2025-01-25 23:21:14,020 [ERROR] visa_bot - VFS Global giriş hatası - Status: 403
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 265
-------------------
2025-01-25 23:21:14,020 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 277
-------------------
2025-01-25 23:21:19,767 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 340
-------------------
2025-01-25 23:21:19,850 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 360
-------------------
2025-01-25 23:21:19,850 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 272
-------------------
2025-01-25 23:21:19,850 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 275
-------------------
2025-01-25 23:21:19,948 [ERROR] visa_bot - VFS Global giriş hatası - Status: 403
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 265
-------------------
2025-01-25 23:21:19,949 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 277
-------------------
2025-01-25 23:22:15,436 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 353
-------------------
2025-01-25 23:22:15,540 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 377
-------------------
2025-01-25 23:22:15,540 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 285
-------------------
2025-01-25 23:22:15,540 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 288
-------------------
2025-01-25 23:22:15,643 [ERROR] visa_bot - VFS Global giriş hatası - Status: 403
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 278
-------------------
2025-01-25 23:22:15,644 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 290
-------------------
2025-01-25 23:23:53,236 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 359
-------------------
2025-01-25 23:23:53,345 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 383
-------------------
2025-01-25 23:23:53,346 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 287
-------------------
2025-01-25 23:23:53,346 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 290
-------------------
2025-01-25 23:23:53,471 [ERROR] visa_bot - Login sayfasına erişilemedi - Status: 403
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 228
-------------------
2025-01-25 23:23:53,472 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 292
-------------------
2025-01-25 23:24:58,394 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 413
-------------------
2025-01-25 23:24:58,496 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 437
-------------------
2025-01-25 23:24:58,496 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 341
-------------------
2025-01-25 23:24:58,496 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 344
-------------------
2025-01-25 23:24:58,585 [ERROR] visa_bot - Ana sayfaya erişilemedi - Status: 403
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 244
-------------------
2025-01-25 23:24:58,586 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 346
-------------------
2025-01-25 23:25:59,347 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 349
-------------------
2025-01-25 23:25:59,454 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 373
-------------------
2025-01-25 23:25:59,454 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 277
-------------------
2025-01-25 23:25:59,454 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 280
-------------------
2025-01-25 23:25:59,594 [ERROR] visa_bot - Randevu kontrolü sırasında hata: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)>
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 273
-------------------
2025-01-25 23:25:59,594 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 282
-------------------
2025-01-25 23:27:01,304 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 358
-------------------
2025-01-25 23:27:01,419 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 382
-------------------
2025-01-25 23:27:01,420 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 286
-------------------
2025-01-25 23:27:01,420 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 289
-------------------
2025-01-25 23:27:07,878 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: session not created: cannot connect to chrome at 127.0.0.1:51339
from session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 131.0.6778.265
Stacktrace:
0   undetected_chromedriver             0x00000001048202a8 undetected_chromedriver + 5538472
1   undetected_chromedriver             0x00000001048181ea undetected_chromedriver + 5505514
2   undetected_chromedriver             0x00000001043396c0 undetected_chromedriver + 399040
3   undetected_chromedriver             0x00000001043781a0 undetected_chromedriver + 655776
4   undetected_chromedriver             0x0000000104377189 undetected_chromedriver + 651657
5   undetected_chromedriver             0x000000010436c61a undetected_chromedriver + 607770
6   undetected_chromedriver             0x00000001043ba63f undetected_chromedriver + 927295
7   undetected_chromedriver             0x00000001043b9c36 undetected_chromedriver + 924726
8   undetected_chromedriver             0x00000001043ae323 undetected_chromedriver + 877347
9   undetected_chromedriver             0x000000010437b1f0 undetected_chromedriver + 668144
10  undetected_chromedriver             0x000000010437c46e undetected_chromedriver + 672878
11  undetected_chromedriver             0x00000001047e54a0 undetected_chromedriver + 5297312
12  undetected_chromedriver             0x00000001047e94c0 undetected_chromedriver + 5313728
13  undetected_chromedriver             0x00000001047c71b7 undetected_chromedriver + 5173687
14  undetected_chromedriver             0x00000001047e9e5e undetected_chromedriver + 5316190
15  undetected_chromedriver             0x00000001047b6b94 undetected_chromedriver + 5106580
16  undetected_chromedriver             0x0000000104806778 undetected_chromedriver + 5433208
17  undetected_chromedriver             0x0000000104806936 undetected_chromedriver + 5433654
18  undetected_chromedriver             0x0000000104817dc8 undetected_chromedriver + 5504456
19  libsystem_pthread.dylib             0x00007ff810397253 _pthread_start + 99
20  libsystem_pthread.dylib             0x00007ff810392bef thread_start + 15

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 282
-------------------
2025-01-25 23:27:07,879 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 291
-------------------
2025-01-25 23:27:26,614 [WARNING] visa_bot - Yetkisiz kullanıcı erişim denemesi - User ID: 6438433218, Username: noname_dev
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 49
-------------------
2025-01-25 23:29:29,358 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 362
-------------------
2025-01-25 23:29:29,476 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 386
-------------------
2025-01-25 23:29:29,476 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 290
-------------------
2025-01-25 23:29:29,476 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 293
-------------------
2025-01-25 23:29:34,772 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: session not created: cannot connect to chrome at 127.0.0.1:51759
from session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 131.0.6778.265
Stacktrace:
0   undetected_chromedriver             0x00000001008852a8 undetected_chromedriver + 5538472
1   undetected_chromedriver             0x000000010087d1ea undetected_chromedriver + 5505514
2   undetected_chromedriver             0x000000010039e6c0 undetected_chromedriver + 399040
3   undetected_chromedriver             0x00000001003dd1a0 undetected_chromedriver + 655776
4   undetected_chromedriver             0x00000001003dc189 undetected_chromedriver + 651657
5   undetected_chromedriver             0x00000001003d161a undetected_chromedriver + 607770
6   undetected_chromedriver             0x000000010041f63f undetected_chromedriver + 927295
7   undetected_chromedriver             0x000000010041ec36 undetected_chromedriver + 924726
8   undetected_chromedriver             0x0000000100413323 undetected_chromedriver + 877347
9   undetected_chromedriver             0x00000001003e01f0 undetected_chromedriver + 668144
10  undetected_chromedriver             0x00000001003e146e undetected_chromedriver + 672878
11  undetected_chromedriver             0x000000010084a4a0 undetected_chromedriver + 5297312
12  undetected_chromedriver             0x000000010084e4c0 undetected_chromedriver + 5313728
13  undetected_chromedriver             0x000000010082c1b7 undetected_chromedriver + 5173687
14  undetected_chromedriver             0x000000010084ee5e undetected_chromedriver + 5316190
15  undetected_chromedriver             0x000000010081bb94 undetected_chromedriver + 5106580
16  undetected_chromedriver             0x000000010086b778 undetected_chromedriver + 5433208
17  undetected_chromedriver             0x000000010086b936 undetected_chromedriver + 5433654
18  undetected_chromedriver             0x000000010087cdc8 undetected_chromedriver + 5504456
19  libsystem_pthread.dylib             0x00007ff810397253 _pthread_start + 99
20  libsystem_pthread.dylib             0x00007ff810392bef thread_start + 15

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 286
-------------------
2025-01-25 23:29:34,772 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 295
-------------------
2025-01-25 23:29:49,178 [INFO] visa_bot - Start komutu alındı - User ID: 6438433218
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 49
-------------------
2025-01-25 23:29:49,178 [INFO] visa_bot - Kullanıcı yetkisi kontrol ediliyor - User ID: 6438433218
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 41
-------------------
2025-01-25 23:29:49,178 [INFO] visa_bot - İzin verilen kullanıcılar: {6438433218}
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 42
-------------------
2025-01-25 23:29:49,178 [INFO] visa_bot - Admin ID: 6438433218
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 43
-------------------
2025-01-25 23:29:57,913 [INFO] visa_bot - Kullanıcı tercihleri ayarlanmaya başlandı - User ID: 6438433218, Username: noname_dev
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 85
-------------------
2025-01-25 23:29:58,216 [DEBUG] visa_bot - Kullanıcı tercihleri başlatıldı - Chat ID: 6438433218
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 98
-------------------
2025-01-25 23:30:27,047 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 367
-------------------
2025-01-25 23:30:27,129 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 391
-------------------
2025-01-25 23:30:27,130 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 295
-------------------
2025-01-25 23:30:27,130 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 298
-------------------
2025-01-25 23:30:30,710 [ERROR] visa_bot - Randevu kontrolü sırasında hata: [Errno 8] Exec format error: '/Users/ibidi/.wdm/drivers/chromedriver/mac64/131.0.6778.264/chromedriver-mac-arm64/THIRD_PARTY_NOTICES.chromedriver'
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 291
-------------------
2025-01-25 23:30:30,710 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 300
-------------------
2025-01-25 23:31:03,122 [DEBUG] visa_bot - Gelen mesaj - User ID: 6438433218, Message: 2
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 109
-------------------
2025-01-25 23:31:08,912 [DEBUG] visa_bot - Gelen mesaj - User ID: 6438433218, Message: Parşova
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 109
-------------------
2025-01-25 23:31:13,381 [DEBUG] visa_bot - Gelen mesaj - User ID: 6438433218, Message: 2025-02-01
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 109
-------------------
2025-01-25 23:31:30,712 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 298
-------------------
2025-01-25 23:31:31,333 [ERROR] visa_bot - Randevu kontrolü sırasında hata: [Errno 8] Exec format error: '/Users/ibidi/.wdm/drivers/chromedriver/mac64/131.0.6778.264/chromedriver-mac-arm64/THIRD_PARTY_NOTICES.chromedriver'
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 291
-------------------
2025-01-25 23:31:31,333 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 300
-------------------
2025-01-25 23:32:31,946 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 374
-------------------
2025-01-25 23:32:32,065 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 398
-------------------
2025-01-25 23:32:32,065 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 302
-------------------
2025-01-25 23:32:32,065 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 305
-------------------
2025-01-25 23:32:32,072 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 298
-------------------
2025-01-25 23:32:32,073 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 307
-------------------
2025-01-25 23:33:32,067 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 305
-------------------
2025-01-25 23:33:32,068 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 298
-------------------
2025-01-25 23:33:32,069 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 307
-------------------
2025-01-25 23:33:47,308 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 374
-------------------
2025-01-25 23:33:47,418 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 398
-------------------
2025-01-25 23:33:47,418 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 302
-------------------
2025-01-25 23:33:47,418 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 305
-------------------
2025-01-25 23:33:53,488 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: Service /opt/homebrew/bin/chromedriver unexpectedly exited. Status code was: -9

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 298
-------------------
2025-01-25 23:33:53,490 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 307
-------------------
2025-01-25 23:34:53,491 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 305
-------------------
2025-01-25 23:34:55,114 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 131.0.6778.265 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Stacktrace:
0   chromedriver                        0x00000001053ee7b8 cxxbridge1$str$ptr + 2598452
1   chromedriver                        0x00000001053e6ff8 cxxbridge1$str$ptr + 2567796
2   chromedriver                        0x0000000104f87f0c cxxbridge1$string$len + 88260
3   chromedriver                        0x0000000104fbdd30 cxxbridge1$string$len + 308968
4   chromedriver                        0x0000000104fbcf0c cxxbridge1$string$len + 305348
5   chromedriver                        0x0000000104fb8a7c cxxbridge1$string$len + 287796
6   chromedriver                        0x0000000104fb4f68 cxxbridge1$string$len + 272672
7   chromedriver                        0x0000000104ff6cc0 cxxbridge1$string$len + 542328
8   chromedriver                        0x0000000104ff6608 cxxbridge1$string$len + 540608
9   chromedriver                        0x0000000104fc0e1c cxxbridge1$string$len + 321492
10  chromedriver                        0x0000000104fc1a64 cxxbridge1$string$len + 324636
11  chromedriver                        0x00000001053b96d4 cxxbridge1$str$ptr + 2381136
12  chromedriver                        0x00000001053bc9f4 cxxbridge1$str$ptr + 2394224
13  chromedriver                        0x00000001053a003c cxxbridge1$str$ptr + 2277048
14  chromedriver                        0x00000001053bd2b4 cxxbridge1$str$ptr + 2396464
15  chromedriver                        0x0000000105391c04 cxxbridge1$str$ptr + 2218624
16  chromedriver                        0x00000001053d7d60 cxxbridge1$str$ptr + 2505692
17  chromedriver                        0x00000001053d7edc cxxbridge1$str$ptr + 2506072
18  chromedriver                        0x00000001053e6c6c cxxbridge1$str$ptr + 2566888
19  libsystem_pthread.dylib             0x00000001860972e4 _pthread_start + 136
20  libsystem_pthread.dylib             0x00000001860920fc thread_start + 8

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 298
-------------------
2025-01-25 23:34:55,115 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 307
-------------------
2025-01-25 23:34:59,412 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 374
-------------------
2025-01-25 23:34:59,526 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 398
-------------------
2025-01-25 23:34:59,527 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 302
-------------------
2025-01-25 23:34:59,527 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 305
-------------------
2025-01-25 23:35:00,521 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 131.0.6778.265 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Stacktrace:
0   chromedriver                        0x00000001012b27b8 cxxbridge1$str$ptr + 2598452
1   chromedriver                        0x00000001012aaff8 cxxbridge1$str$ptr + 2567796
2   chromedriver                        0x0000000100e4bf0c cxxbridge1$string$len + 88260
3   chromedriver                        0x0000000100e81d30 cxxbridge1$string$len + 308968
4   chromedriver                        0x0000000100e80f0c cxxbridge1$string$len + 305348
5   chromedriver                        0x0000000100e7ca7c cxxbridge1$string$len + 287796
6   chromedriver                        0x0000000100e78f68 cxxbridge1$string$len + 272672
7   chromedriver                        0x0000000100ebacc0 cxxbridge1$string$len + 542328
8   chromedriver                        0x0000000100eba608 cxxbridge1$string$len + 540608
9   chromedriver                        0x0000000100e84e1c cxxbridge1$string$len + 321492
10  chromedriver                        0x0000000100e85a64 cxxbridge1$string$len + 324636
11  chromedriver                        0x000000010127d6d4 cxxbridge1$str$ptr + 2381136
12  chromedriver                        0x00000001012809f4 cxxbridge1$str$ptr + 2394224
13  chromedriver                        0x000000010126403c cxxbridge1$str$ptr + 2277048
14  chromedriver                        0x00000001012812b4 cxxbridge1$str$ptr + 2396464
15  chromedriver                        0x0000000101255c04 cxxbridge1$str$ptr + 2218624
16  chromedriver                        0x000000010129bd60 cxxbridge1$str$ptr + 2505692
17  chromedriver                        0x000000010129bedc cxxbridge1$str$ptr + 2506072
18  chromedriver                        0x00000001012aac6c cxxbridge1$str$ptr + 2566888
19  libsystem_pthread.dylib             0x00000001860972e4 _pthread_start + 136
20  libsystem_pthread.dylib             0x00000001860920fc thread_start + 8

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 298
-------------------
2025-01-25 23:35:00,522 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 307
-------------------
2025-01-25 23:36:00,523 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 305
-------------------
2025-01-25 23:36:01,689 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 131.0.6778.265 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Stacktrace:
0   chromedriver                        0x0000000100a2a7b8 cxxbridge1$str$ptr + 2598452
1   chromedriver                        0x0000000100a22ff8 cxxbridge1$str$ptr + 2567796
2   chromedriver                        0x00000001005c3f0c cxxbridge1$string$len + 88260
3   chromedriver                        0x00000001005f9d30 cxxbridge1$string$len + 308968
4   chromedriver                        0x00000001005f8f0c cxxbridge1$string$len + 305348
5   chromedriver                        0x00000001005f4a7c cxxbridge1$string$len + 287796
6   chromedriver                        0x00000001005f0f68 cxxbridge1$string$len + 272672
7   chromedriver                        0x0000000100632cc0 cxxbridge1$string$len + 542328
8   chromedriver                        0x0000000100632608 cxxbridge1$string$len + 540608
9   chromedriver                        0x00000001005fce1c cxxbridge1$string$len + 321492
10  chromedriver                        0x00000001005fda64 cxxbridge1$string$len + 324636
11  chromedriver                        0x00000001009f56d4 cxxbridge1$str$ptr + 2381136
12  chromedriver                        0x00000001009f89f4 cxxbridge1$str$ptr + 2394224
13  chromedriver                        0x00000001009dc03c cxxbridge1$str$ptr + 2277048
14  chromedriver                        0x00000001009f92b4 cxxbridge1$str$ptr + 2396464
15  chromedriver                        0x00000001009cdc04 cxxbridge1$str$ptr + 2218624
16  chromedriver                        0x0000000100a13d60 cxxbridge1$str$ptr + 2505692
17  chromedriver                        0x0000000100a13edc cxxbridge1$str$ptr + 2506072
18  chromedriver                        0x0000000100a22c6c cxxbridge1$str$ptr + 2566888
19  libsystem_pthread.dylib             0x00000001860972e4 _pthread_start + 136
20  libsystem_pthread.dylib             0x00000001860920fc thread_start + 8

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 298
-------------------
2025-01-25 23:36:01,690 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 307
-------------------
2025-01-25 23:37:01,692 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 305
-------------------
2025-01-25 23:37:01,693 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 298
-------------------
2025-01-25 23:37:01,694 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 307
-------------------
2025-01-25 23:37:40,232 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 368
-------------------
2025-01-25 23:37:40,343 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 392
-------------------
2025-01-25 23:37:40,344 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 296
-------------------
2025-01-25 23:37:40,344 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 299
-------------------
2025-01-25 23:37:40,344 [ERROR] visa_bot - Randevu kontrolü sırasında hata: ChromeDriverManager.__init__() got an unexpected keyword argument 'version'
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 292
-------------------
2025-01-25 23:37:40,344 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 301
-------------------
2025-01-25 23:39:03,393 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 369
-------------------
2025-01-25 23:39:03,511 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 393
-------------------
2025-01-25 23:39:03,512 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 297
-------------------
2025-01-25 23:39:03,512 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 300
-------------------
2025-01-25 23:39:12,576 [ERROR] visa_bot - Randevu kontrolü sırasında hata: [Errno 8] Exec format error: '/Users/ibidi/.wdm/drivers/chromedriver/mac64/132.0.6834.110/chromedriver-mac-arm64/THIRD_PARTY_NOTICES.chromedriver'
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 293
-------------------
2025-01-25 23:39:12,576 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 302
-------------------
2025-01-25 23:40:04,772 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 367
-------------------
2025-01-25 23:40:04,877 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 391
-------------------
2025-01-25 23:40:04,878 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 295
-------------------
2025-01-25 23:40:04,878 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 298
-------------------
2025-01-25 23:40:04,878 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: Unable to locate or obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 291
-------------------
2025-01-25 23:40:04,878 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 300
-------------------
2025-01-25 23:40:54,363 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 366
-------------------
2025-01-25 23:40:54,463 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 390
-------------------
2025-01-25 23:40:54,463 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 294
-------------------
2025-01-25 23:40:54,463 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 297
-------------------
2025-01-25 23:41:01,166 [INFO] visa_bot - Login sayfası açılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 233
-------------------
2025-01-25 23:41:12,043 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: 
Stacktrace:
0   chromedriver                        0x00000001010f67b8 cxxbridge1$str$ptr + 2598452
1   chromedriver                        0x00000001010eeff8 cxxbridge1$str$ptr + 2567796
2   chromedriver                        0x0000000100c8ff0c cxxbridge1$string$len + 88260
3   chromedriver                        0x0000000100cd5000 cxxbridge1$string$len + 371128
4   chromedriver                        0x0000000100d0f148 cxxbridge1$string$len + 609024
5   chromedriver                        0x0000000100cc8e1c cxxbridge1$string$len + 321492
6   chromedriver                        0x0000000100cc9a64 cxxbridge1$string$len + 324636
7   chromedriver                        0x00000001010c16d4 cxxbridge1$str$ptr + 2381136
8   chromedriver                        0x00000001010c49f4 cxxbridge1$str$ptr + 2394224
9   chromedriver                        0x00000001010a803c cxxbridge1$str$ptr + 2277048
10  chromedriver                        0x00000001010c52b4 cxxbridge1$str$ptr + 2396464
11  chromedriver                        0x0000000101099c04 cxxbridge1$str$ptr + 2218624
12  chromedriver                        0x00000001010dfd60 cxxbridge1$str$ptr + 2505692
13  chromedriver                        0x00000001010dfedc cxxbridge1$str$ptr + 2506072
14  chromedriver                        0x00000001010eec6c cxxbridge1$str$ptr + 2566888
15  libsystem_pthread.dylib             0x00000001860972e4 _pthread_start + 136
16  libsystem_pthread.dylib             0x00000001860920fc thread_start + 8

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 290
-------------------
2025-01-25 23:41:12,044 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 299
-------------------
2025-01-25 23:42:12,046 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 297
-------------------
2025-01-25 23:42:13,875 [INFO] visa_bot - Login sayfası açılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 233
-------------------
2025-01-25 23:42:24,335 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: 
Stacktrace:
0   chromedriver                        0x00000001049027b8 cxxbridge1$str$ptr + 2598452
1   chromedriver                        0x00000001048faff8 cxxbridge1$str$ptr + 2567796
2   chromedriver                        0x000000010449bf0c cxxbridge1$string$len + 88260
3   chromedriver                        0x00000001044e1000 cxxbridge1$string$len + 371128
4   chromedriver                        0x000000010451b148 cxxbridge1$string$len + 609024
5   chromedriver                        0x00000001044d4e1c cxxbridge1$string$len + 321492
6   chromedriver                        0x00000001044d5a64 cxxbridge1$string$len + 324636
7   chromedriver                        0x00000001048cd6d4 cxxbridge1$str$ptr + 2381136
8   chromedriver                        0x00000001048d09f4 cxxbridge1$str$ptr + 2394224
9   chromedriver                        0x00000001048b403c cxxbridge1$str$ptr + 2277048
10  chromedriver                        0x00000001048d12b4 cxxbridge1$str$ptr + 2396464
11  chromedriver                        0x00000001048a5c04 cxxbridge1$str$ptr + 2218624
12  chromedriver                        0x00000001048ebd60 cxxbridge1$str$ptr + 2505692
13  chromedriver                        0x00000001048ebedc cxxbridge1$str$ptr + 2506072
14  chromedriver                        0x00000001048fac6c cxxbridge1$str$ptr + 2566888
15  libsystem_pthread.dylib             0x00000001860972e4 _pthread_start + 136
16  libsystem_pthread.dylib             0x00000001860920fc thread_start + 8

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 290
-------------------
2025-01-25 23:42:24,337 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 299
-------------------
2025-01-25 23:42:34,019 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 369
-------------------
2025-01-25 23:42:34,124 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 393
-------------------
2025-01-25 23:42:34,124 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 297
-------------------
2025-01-25 23:42:34,124 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 300
-------------------
2025-01-25 23:42:35,105 [INFO] visa_bot - Login sayfası açılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 236
-------------------
2025-01-25 23:42:45,539 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: 
Stacktrace:
0   chromedriver                        0x00000001052267b8 cxxbridge1$str$ptr + 2598452
1   chromedriver                        0x000000010521eff8 cxxbridge1$str$ptr + 2567796
2   chromedriver                        0x0000000104dbff0c cxxbridge1$string$len + 88260
3   chromedriver                        0x0000000104e05000 cxxbridge1$string$len + 371128
4   chromedriver                        0x0000000104e3f148 cxxbridge1$string$len + 609024
5   chromedriver                        0x0000000104df8e1c cxxbridge1$string$len + 321492
6   chromedriver                        0x0000000104df9a64 cxxbridge1$string$len + 324636
7   chromedriver                        0x00000001051f16d4 cxxbridge1$str$ptr + 2381136
8   chromedriver                        0x00000001051f49f4 cxxbridge1$str$ptr + 2394224
9   chromedriver                        0x00000001051d803c cxxbridge1$str$ptr + 2277048
10  chromedriver                        0x00000001051f52b4 cxxbridge1$str$ptr + 2396464
11  chromedriver                        0x00000001051c9c04 cxxbridge1$str$ptr + 2218624
12  chromedriver                        0x000000010520fd60 cxxbridge1$str$ptr + 2505692
13  chromedriver                        0x000000010520fedc cxxbridge1$str$ptr + 2506072
14  chromedriver                        0x000000010521ec6c cxxbridge1$str$ptr + 2566888
15  libsystem_pthread.dylib             0x00000001860972e4 _pthread_start + 136
16  libsystem_pthread.dylib             0x00000001860920fc thread_start + 8

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 293
-------------------
2025-01-25 23:42:45,540 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 302
-------------------
2025-01-25 23:43:45,542 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 300
-------------------
2025-01-25 23:43:46,880 [INFO] visa_bot - Login sayfası açılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 236
-------------------
2025-01-25 23:44:09,482 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 364
-------------------
2025-01-25 23:44:09,600 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 388
-------------------
2025-01-25 23:44:09,600 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 292
-------------------
2025-01-25 23:44:09,600 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 295
-------------------
2025-01-25 23:44:15,756 [INFO] visa_bot - Login sayfası açılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 231
-------------------
2025-01-25 23:44:26,561 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: 
Stacktrace:
0   undetected_chromedriver             0x0000000104aca2a8 undetected_chromedriver + 5538472
1   undetected_chromedriver             0x0000000104ac21ea undetected_chromedriver + 5505514
2   undetected_chromedriver             0x00000001045e36c0 undetected_chromedriver + 399040
3   undetected_chromedriver             0x0000000104633653 undetected_chromedriver + 726611
4   undetected_chromedriver             0x0000000104633891 undetected_chromedriver + 727185
5   undetected_chromedriver             0x000000010467a184 undetected_chromedriver + 1016196
6   undetected_chromedriver             0x00000001046585ad undetected_chromedriver + 877997
7   undetected_chromedriver             0x0000000104677497 undetected_chromedriver + 1004695
8   undetected_chromedriver             0x0000000104658323 undetected_chromedriver + 877347
9   undetected_chromedriver             0x00000001046251f0 undetected_chromedriver + 668144
10  undetected_chromedriver             0x000000010462646e undetected_chromedriver + 672878
11  undetected_chromedriver             0x0000000104a8f4a0 undetected_chromedriver + 5297312
12  undetected_chromedriver             0x0000000104a934c0 undetected_chromedriver + 5313728
13  undetected_chromedriver             0x0000000104a711b7 undetected_chromedriver + 5173687
14  undetected_chromedriver             0x0000000104a93e5e undetected_chromedriver + 5316190
15  undetected_chromedriver             0x0000000104a60b94 undetected_chromedriver + 5106580
16  undetected_chromedriver             0x0000000104ab0778 undetected_chromedriver + 5433208
17  undetected_chromedriver             0x0000000104ab0936 undetected_chromedriver + 5433654
18  undetected_chromedriver             0x0000000104ac1dc8 undetected_chromedriver + 5504456
19  libsystem_pthread.dylib             0x00007ff810397253 _pthread_start + 99
20  libsystem_pthread.dylib             0x00007ff810392bef thread_start + 15

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 288
-------------------
2025-01-25 23:44:26,561 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 297
-------------------
2025-01-25 23:45:26,563 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 295
-------------------
2025-01-25 23:45:31,415 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: Service /Users/ibidi/Library/Application Support/undetected_chromedriver/undetected_chromedriver unexpectedly exited. Status code was: -2

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 288
-------------------
2025-01-25 23:45:31,415 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 297
-------------------
2025-01-25 23:45:34,200 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 368
-------------------
2025-01-25 23:45:34,322 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 392
-------------------
2025-01-25 23:45:34,322 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 296
-------------------
2025-01-25 23:45:34,322 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 299
-------------------
2025-01-25 23:45:39,896 [INFO] visa_bot - Login sayfası açılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 235
-------------------
2025-01-25 23:45:50,859 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: 
Stacktrace:
0   undetected_chromedriver             0x00000001010f22a8 undetected_chromedriver + 5538472
1   undetected_chromedriver             0x00000001010ea1ea undetected_chromedriver + 5505514
2   undetected_chromedriver             0x0000000100c0b6c0 undetected_chromedriver + 399040
3   undetected_chromedriver             0x0000000100c5b653 undetected_chromedriver + 726611
4   undetected_chromedriver             0x0000000100c5b891 undetected_chromedriver + 727185
5   undetected_chromedriver             0x0000000100ca2184 undetected_chromedriver + 1016196
6   undetected_chromedriver             0x0000000100c805ad undetected_chromedriver + 877997
7   undetected_chromedriver             0x0000000100c9f497 undetected_chromedriver + 1004695
8   undetected_chromedriver             0x0000000100c80323 undetected_chromedriver + 877347
9   undetected_chromedriver             0x0000000100c4d1f0 undetected_chromedriver + 668144
10  undetected_chromedriver             0x0000000100c4e46e undetected_chromedriver + 672878
11  undetected_chromedriver             0x00000001010b74a0 undetected_chromedriver + 5297312
12  undetected_chromedriver             0x00000001010bb4c0 undetected_chromedriver + 5313728
13  undetected_chromedriver             0x00000001010991b7 undetected_chromedriver + 5173687
14  undetected_chromedriver             0x00000001010bbe5e undetected_chromedriver + 5316190
15  undetected_chromedriver             0x0000000101088b94 undetected_chromedriver + 5106580
16  undetected_chromedriver             0x00000001010d8778 undetected_chromedriver + 5433208
17  undetected_chromedriver             0x00000001010d8936 undetected_chromedriver + 5433654
18  undetected_chromedriver             0x00000001010e9dc8 undetected_chromedriver + 5504456
19  libsystem_pthread.dylib             0x00007ff810397253 _pthread_start + 99
20  libsystem_pthread.dylib             0x00007ff810392bef thread_start + 15

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 292
-------------------
2025-01-25 23:45:50,859 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 301
-------------------
2025-01-25 23:46:42,159 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 367
-------------------
2025-01-25 23:46:42,266 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 391
-------------------
2025-01-25 23:46:42,266 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 295
-------------------
2025-01-25 23:46:42,266 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 298
-------------------
2025-01-25 23:46:43,348 [INFO] visa_bot - Login sayfası açılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 234
-------------------
2025-01-25 23:46:53,991 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: 
Stacktrace:
0   chromedriver                        0x0000000102e5a7b8 cxxbridge1$str$ptr + 2598452
1   chromedriver                        0x0000000102e52ff8 cxxbridge1$str$ptr + 2567796
2   chromedriver                        0x00000001029f3f0c cxxbridge1$string$len + 88260
3   chromedriver                        0x0000000102a39000 cxxbridge1$string$len + 371128
4   chromedriver                        0x0000000102a73148 cxxbridge1$string$len + 609024
5   chromedriver                        0x0000000102a2ce1c cxxbridge1$string$len + 321492
6   chromedriver                        0x0000000102a2da64 cxxbridge1$string$len + 324636
7   chromedriver                        0x0000000102e256d4 cxxbridge1$str$ptr + 2381136
8   chromedriver                        0x0000000102e289f4 cxxbridge1$str$ptr + 2394224
9   chromedriver                        0x0000000102e0c03c cxxbridge1$str$ptr + 2277048
10  chromedriver                        0x0000000102e292b4 cxxbridge1$str$ptr + 2396464
11  chromedriver                        0x0000000102dfdc04 cxxbridge1$str$ptr + 2218624
12  chromedriver                        0x0000000102e43d60 cxxbridge1$str$ptr + 2505692
13  chromedriver                        0x0000000102e43edc cxxbridge1$str$ptr + 2506072
14  chromedriver                        0x0000000102e52c6c cxxbridge1$str$ptr + 2566888
15  libsystem_pthread.dylib             0x00000001860972e4 _pthread_start + 136
16  libsystem_pthread.dylib             0x00000001860920fc thread_start + 8

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 291
-------------------
2025-01-25 23:46:53,992 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 300
-------------------
2025-01-25 23:47:55,245 [INFO] visa_bot - Bot başlatılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 371
-------------------
2025-01-25 23:47:55,379 [INFO] visa_bot - Bot hazır, çalışmaya başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 395
-------------------
2025-01-25 23:47:55,379 [INFO] visa_bot - Randevu kontrol zamanlayıcısı başlatıldı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 299
-------------------
2025-01-25 23:47:55,380 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 302
-------------------
2025-01-25 23:47:56,895 [INFO] visa_bot - Login sayfası açılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 238
-------------------
2025-01-25 23:48:07,395 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: 
Stacktrace:
0   chromedriver                        0x0000000102c027b8 cxxbridge1$str$ptr + 2598452
1   chromedriver                        0x0000000102bfaff8 cxxbridge1$str$ptr + 2567796
2   chromedriver                        0x000000010279bf0c cxxbridge1$string$len + 88260
3   chromedriver                        0x00000001027e1000 cxxbridge1$string$len + 371128
4   chromedriver                        0x000000010281b148 cxxbridge1$string$len + 609024
5   chromedriver                        0x00000001027d4e1c cxxbridge1$string$len + 321492
6   chromedriver                        0x00000001027d5a64 cxxbridge1$string$len + 324636
7   chromedriver                        0x0000000102bcd6d4 cxxbridge1$str$ptr + 2381136
8   chromedriver                        0x0000000102bd09f4 cxxbridge1$str$ptr + 2394224
9   chromedriver                        0x0000000102bb403c cxxbridge1$str$ptr + 2277048
10  chromedriver                        0x0000000102bd12b4 cxxbridge1$str$ptr + 2396464
11  chromedriver                        0x0000000102ba5c04 cxxbridge1$str$ptr + 2218624
12  chromedriver                        0x0000000102bebd60 cxxbridge1$str$ptr + 2505692
13  chromedriver                        0x0000000102bebedc cxxbridge1$str$ptr + 2506072
14  chromedriver                        0x0000000102bfac6c cxxbridge1$str$ptr + 2566888
15  libsystem_pthread.dylib             0x00000001860972e4 _pthread_start + 136
16  libsystem_pthread.dylib             0x00000001860920fc thread_start + 8

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 295
-------------------
2025-01-25 23:48:07,397 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 304
-------------------
2025-01-25 23:49:07,399 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 302
-------------------
2025-01-25 23:49:08,979 [INFO] visa_bot - Login sayfası açılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 238
-------------------
2025-01-25 23:49:19,576 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: 
Stacktrace:
0   chromedriver                        0x000000010304e7b8 cxxbridge1$str$ptr + 2598452
1   chromedriver                        0x0000000103046ff8 cxxbridge1$str$ptr + 2567796
2   chromedriver                        0x0000000102be7f0c cxxbridge1$string$len + 88260
3   chromedriver                        0x0000000102c2d000 cxxbridge1$string$len + 371128
4   chromedriver                        0x0000000102c67148 cxxbridge1$string$len + 609024
5   chromedriver                        0x0000000102c20e1c cxxbridge1$string$len + 321492
6   chromedriver                        0x0000000102c21a64 cxxbridge1$string$len + 324636
7   chromedriver                        0x00000001030196d4 cxxbridge1$str$ptr + 2381136
8   chromedriver                        0x000000010301c9f4 cxxbridge1$str$ptr + 2394224
9   chromedriver                        0x000000010300003c cxxbridge1$str$ptr + 2277048
10  chromedriver                        0x000000010301d2b4 cxxbridge1$str$ptr + 2396464
11  chromedriver                        0x0000000102ff1c04 cxxbridge1$str$ptr + 2218624
12  chromedriver                        0x0000000103037d60 cxxbridge1$str$ptr + 2505692
13  chromedriver                        0x0000000103037edc cxxbridge1$str$ptr + 2506072
14  chromedriver                        0x0000000103046c6c cxxbridge1$str$ptr + 2566888
15  libsystem_pthread.dylib             0x00000001860972e4 _pthread_start + 136
16  libsystem_pthread.dylib             0x00000001860920fc thread_start + 8

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 295
-------------------
2025-01-25 23:49:19,577 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 304
-------------------
2025-01-25 23:50:19,579 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 302
-------------------
2025-01-25 23:50:20,975 [INFO] visa_bot - Login sayfası açılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 238
-------------------
2025-01-25 23:50:31,475 [ERROR] visa_bot - Randevu kontrolü sırasında hata: Message: 
Stacktrace:
0   chromedriver                        0x0000000100d127b8 cxxbridge1$str$ptr + 2598452
1   chromedriver                        0x0000000100d0aff8 cxxbridge1$str$ptr + 2567796
2   chromedriver                        0x00000001008abf0c cxxbridge1$string$len + 88260
3   chromedriver                        0x00000001008f1000 cxxbridge1$string$len + 371128
4   chromedriver                        0x000000010092b148 cxxbridge1$string$len + 609024
5   chromedriver                        0x00000001008e4e1c cxxbridge1$string$len + 321492
6   chromedriver                        0x00000001008e5a64 cxxbridge1$string$len + 324636
7   chromedriver                        0x0000000100cdd6d4 cxxbridge1$str$ptr + 2381136
8   chromedriver                        0x0000000100ce09f4 cxxbridge1$str$ptr + 2394224
9   chromedriver                        0x0000000100cc403c cxxbridge1$str$ptr + 2277048
10  chromedriver                        0x0000000100ce12b4 cxxbridge1$str$ptr + 2396464
11  chromedriver                        0x0000000100cb5c04 cxxbridge1$str$ptr + 2218624
12  chromedriver                        0x0000000100cfbd60 cxxbridge1$str$ptr + 2505692
13  chromedriver                        0x0000000100cfbedc cxxbridge1$str$ptr + 2506072
14  chromedriver                        0x0000000100d0ac6c cxxbridge1$str$ptr + 2566888
15  libsystem_pthread.dylib             0x00000001860972e4 _pthread_start + 136
16  libsystem_pthread.dylib             0x00000001860920fc thread_start + 8

File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 295
-------------------
2025-01-25 23:50:31,476 [DEBUG] visa_bot - Randevu kontrolü tamamlandı
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 304
-------------------
2025-01-25 23:51:31,463 [DEBUG] visa_bot - Randevu kontrolü başlıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 302
-------------------
2025-01-25 23:51:32,902 [INFO] visa_bot - Login sayfası açılıyor...
File "/Users/ibidi/Desktop/vize/sevgililer-günü/schengen-visa-bot/bot.py", line 238
-------------------
